

CREATE OR REPLACE PROCEDURE proc_reporting (ETAT in varchar2)  as

begin


  delete from REPORTING_REASS  where STATUT=ETAT;

  insert  into  REPORTING_REASS
   
   --  create table REPORTING_REASS  as
(select 
CODEINTE,NUMEPOLI,NUMEAVEN,
CODEBRAN,
LIBEREASS_CL,
LIBEREASS_EDP,
LIBEREASS_FAC,
 SOURCE,
 'AVANT CORRECTION' STATUT,
 sum(PRIME_CEDEE_CL) PRIME_CEDEE_CL,
 sum(PRIME_CEDEE_FAC) PRIME_CEDEE_FAC,
 
 sum(PRIME_CEDEE_EDP) PRIME_CEDEE_EDP


from

(
select
ID_GARANTIE, SOURCE,i.CODEINTE,i.NUMEPOLI, i.NUMEAVEN,CODEBRAN,
LIBEREASS_CL,
LIBEREASS_EDP,
LIBEREASS_FAC,

CAPITAUX_100,
SMP_100,
PRM_NT_100,

taux_cl,
PRIME_CEDEE_cl,

taux_fac,
PRIME_CEDEE_fac,

taux_edp,
PRIME_CEDEE_edp,

taux_retention,
 PRIME_RETENTION,
 PRIME_DECOUVERT


from
(

select 
ID_GARANTIE, SOURCE,CODEINTE,NUMEPOLI, NUMEAVEN,

max(ID_REASSURANCE_cl)  ID_REASSURANCE_cl,
max(ID_REASSURANCE_fac) ID_REASSURANCE_fac,
max(ID_REASSURANCE_edp) ID_REASSURANCE_edp,

max(CAPITAUX_100) CAPITAUX_100,
max(SMP_100)  SMP_100,
max(PRM_NT_100) PRM_NT_100,

max(taux_cl) taux_cl,
sum(PRIME_CEDEE_cl) PRIME_CEDEE_cl,

max(taux_fac) taux_fac,
sum(PRIME_CEDEE_fac) PRIME_CEDEE_fac,

max(taux_edp) taux_edp,
sum(PRIME_CEDEE_edp) PRIME_CEDEE_edp,

max(taux_retention) taux_retention,
sum(PRIME_RETENTION) PRIME_RETENTION,
sum(PRIME_DECOUVERT) PRIME_DECOUVERT

from SAT_OUTPUT_REASS  where STATUT='ACTIF'

GROUP BY
ID_GARANTIE, SOURCE,CODEINTE,NUMEPOLI, NUMEAVEN
)i,
(select distinct MAX(CODEBRAN)CODEBRAN ,CODEINTE,NUMEPOLI,nvl(NUMEAVEN,0) NUMEAVEN from ORASS_V6.V_CH_AFFAIRE 
group by CODEINTE,NUMEPOLI,NUMEAVEN)j
,

(select distinct ID_REASSURANCE,MAX(LIBEREASS) LIBEREASS_CL from  SAT_REASSURANCE where STATUT='ACTIF' group by ID_REASSURANCE)CL,
(select distinct ID_REASSURANCE,max(LIBEREASS ) LIBEREASS_EDP from  SAT_REASSURANCE where STATUT='ACTIF' group by ID_REASSURANCE)EDP,
(select distinct ID_REASSURANCE,max(LIBEREASS) LIBEREASS_FAC from  SAT_REASSURANCE where STATUT='ACTIF' group by ID_REASSURANCE)FAC

where 
       i.CODEINTE= j.CODEINTE(+)
and    i.NUMEPOLI= j.NUMEPOLI (+)
and    i.NUMEAVEN= j.NUMEAVEN(+)
and    i.ID_REASSURANCE_cl= CL.ID_REASSURANCE(+)
and    i.ID_REASSURANCE_fac= FAC.ID_REASSURANCE(+)
and    i.ID_REASSURANCE_edp= EDP.ID_REASSURANCE(+)
)

group by

 CODEINTE,NUMEPOLI,NUMEAVEN,
 CODEBRAN,
 LIBEREASS_CL,
LIBEREASS_EDP,
LIBEREASS_FAC,'AVANT CORRECTION',
 SOURCE

---order by
---
--- CODEINTE,NUMEPOLI,NUMEAVEN,
--- CODEBRAN,
--- LIBEREASS_CL,
---LIBEREASS_EDP,
---LIBEREASS_FAC,
--- SOURCE,
--- 'AV CORRECTION'
)
;

commit;
end;