

DROP TABLE REASS_DB.SAT_INTERMEDIAIRE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_INTERMEDIAIRE
(
  ID_INTERMEDIAIRE      VARCHAR2(1000 BYTE)     NOT NULL,
  DATE_INS              DATE,
  DATE_FIN             DATE,
  SOURCE                VARCHAR2(1000 BYTE),
  ID_SAT_INTERMEDIAIRE   VARCHAR2(1000 BYTE),
  CODEINTE              VARCHAR2(255 BYTE),
  TYPE_INTER            VARCHAR2(1000 BYTE),
  RAISON                VARCHAR2(1000 BYTE)
)


--DROP TABLE REASS_DB.RISQUES 

DROP TABLE REASS_DB.SAT_POLICE_AVENANT CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_POLICE_AVENANT
(
   ID_POLICE_AVENANT              VARCHAR2(255 BYTE),
  DATE_INS                       DATE,
  DATE_FIN                       DATE,
  SOURCE                          VARCHAR2(255 BYTE),
  ID_SAT_POLICE_AVENANT          VARCHAR2(4000 BYTE),
  CODEINTE                       VARCHAR2(255 BYTE),
  NUMEPOLI                       VARCHAR2(255 BYTE),
  CODECATE                       FLOAT(126),
  NUMEAVEN                       VARCHAR2(255 BYTE),
  DATEEFFE                       VARCHAR2(255 BYTE),
  DATEECHE                       VARCHAR2(255 BYTE),
  DATECOMP                       VARCHAR2(255 BYTE),
  GARANTIE_IDENTIQUE_PAR_RISQUE  NUMBER,
  STATUT                         VARCHAR2(255 BYTE)
  

)

DROP TABLE REASS_DB.HUB_GARANTIE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.HUB_GARANTIE
(
  ID_GARANTIE        VARCHAR2(255 BYTE),
  DATE_INS           DATE,
  SOURCE             VARCHAR2( 255 BYTE),
  --CODE_GARANTIE_REF  VARCHAR2(255 BYTE)
  --STATUT            VARCHAR2(255 BYTE)
  CODEINTE     VARCHAR( 255 BYTE),
  NUMEPOLI     VARCHAR( 255 BYTE),
   NUMEAVEN  VARCHAR( 255 BYTE),
  CODERISQ     VARCHAR( 255 BYTE),
  CODEGARA     VARCHAR( 255 BYTE)
)


DROP TABLE REASS_DB.SAT_GARANTIE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_GARANTIE
(
  ID_GARANTIE      VARCHAR2(255 BYTE),
  DATE_INS         DATE,
  DATE_FIN             DATE,
  SOURCE           VARCHAR2(255 BYTE),
  ID_SAT_GARANTIE  VARCHAR2(255 BYTE),
   CODEINTE     VARCHAR( 255 BYTE),
  NUMEPOLI     VARCHAR( 255 BYTE),
   NUMEAVEN  VARCHAR( 255 BYTE),
  --CODERISQ     VARCHAR( 255 BYTE),
 -- CODEGARA     VARCHAR( 255 BYTE)

  --CODE_GARANTIE_REF VARCHAR2(255 BYTE),
  --NUMEPOLI           FLOAT(126),
  --CODEINTE           INTEGER,
  --NUMEAVEN           INTEGER,
  --DATECOMP           VARCHAR2(255 BYTE),
  --DATEEFFE           VARCHAR2(255 BYTE),
  --DATEECHE           VARCHAR2(255 BYTE),
  --CODECATE           INTEGER,
  --LIBECATE           VARCHAR2(255 BYTE),
  --CODEBRAN           INTEGER,
  --LIBEBRAN           VARCHAR2(255 BYTE),
  CODEGARA           VARCHAR2(255 BYTE),
  LIBEL_BRAN_RE      VARCHAR2(255 BYTE),
  --LIBERISQ           VARCHAR2(255 BYTE),
  CODERISQ            VARCHAR2(255 BYTE),
  --LIBECLASS          VARCHAR2(255 BYTE),
  --CLASS_RISQ         VARCHAR2(255 BYTE),
  --PRCT_RED_CPCT      INTEGER,
  CAPITAUX           FLOAT(126),
  SMP                FLOAT(126),
  PRM_NT             FLOAT(126),
  STATUT           VARCHAR2(255 BYTE)
)


DROP TABLE REASS_DB.HUB_RISQUE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.HUB_RISQUE
(
  ID_RISQUE  VARCHAR2(255 BYTE),
  DATE_INS   DATE,
  SOURCE     VARCHAR( 255 BYTE),
  CODEINTE     VARCHAR( 255 BYTE),
  NUMEPOLI     VARCHAR( 255 BYTE),
  CODERISQ     VARCHAR( 255 BYTE)
 --- CODE_RISQUE_REF     VARCHAR( 255 BYTE)
)


DROP TABLE REASS_DB.SAT_RISQUE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_RISQUE
(
  ID_RISQUE      VARCHAR2(255 BYTE),
  DATE_INS       DATE,
  DATE_FIN             DATE,
  SOURCE         VARCHAR2(300 BYTE),
  ID_SAT_RISQUE  VARCHAR2(300 BYTE),
  CODEINTE       VARCHAR2(255 BYTE),
  NUMEPOLI       VARCHAR2(255 BYTE),
  --NUMEAVEN       INTEGER,
  CODERISQ       INTEGER,
  --DATEEFFE       VARCHAR2(255 BYTE),
 -- DATEECHE       VARCHAR2(255 BYTE),
   OBSECOMM   VARCHAR2(255 BYTE),
   ADRERISQ  VARCHAR2(255 BYTE),
  LIBERISQ       VARCHAR2(255 BYTE),
  CLASS_RISQUE     VARCHAR2(255 BYTE),
  LIBECLASS      VARCHAR2(255 BYTE),
 -- CODE_RISQUE_REF VARCHAR2(255 BYTE),
---  PRCT_RED_CPCT float(126) ,
  STATUT            VARCHAR2(255 BYTE)
)
COMMIT;

DROP TABLE REASS_DB.LINK_FAC CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.LINK_FAC
(
  ID_FAC             VARCHAR2(1000 BYTE),
  ID_POLICE_AVENANT  NUMBER,
  ID_REASSUREUR      VARCHAR2(1000 BYTE),
  DATE_INS           DATE,
  SOURCE             VARCHAR2(1000 BYTE),
  ID_GARANTIE        NUMBER,
  ID_RISQUE          NUMBER
  , STATUT         VARCHAR2(255 BYTE)
)

DROP TABLE REASS_DB.LINK_AVENANT_RISQ_GARANTIE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.LINK_AVENANT_RISQ_GARANTIE
(
  ID_GARANTIE        VARCHAR2(255 BYTE),
  ID_POLICE_AVENANT  VARCHAR2(255 BYTE),
  ID_LINK_AVENANT_RISQ_GARANTIE VARCHAR2(255 BYTE),
  DATE_INS           DATE,
  DATE_FIN          DATE,
  SOURCE             VARCHAR2(300 BYTE),
  ID_RISQUE          VARCHAR2(255 BYTE),
  STATUT         VARCHAR2(255 BYTE)
)


--DROP TABLE REASS_DB.RISQUES


DROP TABLE REASS_DB.SAT_CLIENT CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_CLIENT
(
  ID_CLIENT      VARCHAR2(255 BYTE)            NOT NULL,
  DATE_INS       DATE,
  DATE_FIN             DATE,
  SOURCE         VARCHAR2(1000 BYTE),
  ID_SAT_CLIENT   VARCHAR2(255 BYTE),
  CODEASSU       VARCHAR2(255 BYTE),
  NOM            VARCHAR2(255 BYTE),
  PRENOMS        VARCHAR2(255 BYTE),
  ACTIVITE       VARCHAR2(255 BYTE),
  STATUT         VARCHAR2(255 BYTE)
)


DROP TABLE REASS_DB.SAT_COASSURANCE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_COASSURANCE
(
  ID_COASSURANCE      VARCHAR2(1000 BYTE),
  DATE_INS            DATE,
    DATE_FIN            DATE,
  SOURCE              VARCHAR2(255 BYTE),
  ID_SAT_COASSURANCE  VARCHAR2(255 BYTE),
  NUMEPOLI           VARCHAR2(255 BYTE),
  CODEINTE            VARCHAR2(255 BYTE),
  NUMEAVEN            VARCHAR2(255 BYTE),
  DATEEFFE            VARCHAR2(255 BYTE),
  DATEECHE            VARCHAR2(255 BYTE),
  DATECOMP            VARCHAR2(255 BYTE),
  STATUT_COASS              VARCHAR2(255 BYTE),
  NOM_COASSUREUR      VARCHAR2(255 BYTE),
  TAUX_COASS          FLOAT(126)
   ,STATUT            VARCHAR2(255 BYTE)
)

DROP TABLE REASS_DB.LINK_COASS CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.LINK_COASS
(
  ID_COASSURANCE     VARCHAR2(1000 BYTE)        NOT NULL,
  --ID_COASSUREUR      VARCHAR2(1000 BYTE),
  ID_POLICE_AVENANT  VARCHAR2(1000 BYTE),
  DATE_INS           DATE                       DEFAULT SYSDATE,
  SOURCE             VARCHAR2(255 BYTE)
  ,STATUT            VARCHAR2(255 BYTE)
)


DROP TABLE REASS_DB.LINK_INTER_CLIENT_POLICE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.LINK_INTER_CLIENT_POLICE
(
  ID_POLICE_AVENANT   VARCHAR2(1000 BYTE)        NOT NULL,
  DATE_INS           DATE                       DEFAULT SYSDATE,
  DATE_FIN           DATE    ,
  SOURCE             VARCHAR2(255 BYTE),
  ID_CLIENT          VARCHAR2(255 BYTE),
  --ID_POLICE_AVENANT  VARCHAR2(255 BYTE),
  ID_INTERMEDIAIRE   VARCHAR2(255 BYTE),
  ID_LINK_IN_CL_POLICE VARCHAR2(255 BYTE)
    , STATUT         VARCHAR2(255 BYTE)
)

DROP TABLE REASS_DB.FACULTATIVE


DROP TABLE REASS_DB.HUB_FAC CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.HUB_FAC
(
  ID_FAC    VARCHAR2(1000 BYTE)                    NOT NULL,
  DATE_INS  DATE                                DEFAULT SYSDATE,
  SOURCE    VARCHAR2(255 BYTE) ,
  CODE_FAC   VARCHAR2(255 BYTE)
)

CREATE TABLE REASS_DB.HUB_REASSURANCE
(
  ID_FAC    VARCHAR2(1000 BYTE)                    NOT NULL,
  DATE_INS  DATE                                DEFAULT SYSDATE,
  SOURCE    VARCHAR2(255 BYTE) ,
  CODE_FAC   VARCHAR2(255 BYTE)
)


DROP TABLE REASS_DB.SAT_POLICE_AVENANT CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_POLICE_AVENANT
(
  ID_POLICE_AVENANT      VARCHAR2(255 BYTE),
  DATE_INS               DATE,
  SOURCE                 VARCHAR2(255 BYTE),
  ID_SAT_POLICE_AVENANT  NUMBER,
  CODEINTE               VARCHAR2(255 BYTE),
  NUMEPOLI               VARCHAR2(255 BYTE),
  NUMEAVEN               VARCHAR2(255 BYTE),
  DATEEFFE               VARCHAR2(255 BYTE),
  DATEECHE               VARCHAR2(255 BYTE),
  DATECOMP               VARCHAR2(255 BYTE),
 -- TAUX_CL                NUMBER,
  GARANTIE_IDENTIQUE_PAR_RISQUE  NUMBER,
  STATUT         VARCHAR2(255 BYTE)
)

DROP TABLE REASS_DB.HUB_POLICE_AVENANT CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.HUB_POLICE_AVENANT
(
  ID_POLICE_AVENANT  VARCHAR2(255 BYTE),
  DATE_INS           DATE,
  SOURCE             VARCHAR2(226 BYTE),
  CODEINTE           VARCHAR2(255 BYTE),
  NUMEPOLI           VARCHAR2(255 BYTE),
  NUMEAVEN           VARCHAR2(255 BYTE)
    ---STATUT            VARCHAR2(2226 BYTE)
)

;


DROP TABLE LINK_COASS_CESSION_COASSUREUR ;
CREATE TABLE LINK_COASS_CESSION_COASSUREUR 
 ( 
     ID_COASSUREUR  VARCHAR2(255 BYTE),   
     ID_COASSURANCE VARCHAR2(255 BYTE),  
     ID_POLICE_AVENANT VARCHAR2(255 BYTE),
     ID_LINK_CESSION_COASSUREUR VARCHAR2(255 BYTE),
     DATE_INS  DATE,    
       DATE_FIN  DATE,     
     SOURCE    VARCHAR2(2226 BYTE)
    , STATUT         VARCHAR2(255 BYTE)
 )


DROP TABLE REASS_DB.SAT_LINK_COASS_CES_COASSUREUR ;
CREATE TABLE REASS_DB.SAT_LINK_COASS_CES_COASSUREUR 
 ( 
     ID_COASSUREUR  VARCHAR2(255 BYTE),   
     ID_COASSURANCE VARCHAR2(255 BYTE),  
     ID_POLICE_AVENANT VARCHAR2(255 BYTE),
     DATE_INS  DATE,  
     DATE_FIN             DATE,      
     SOURCE    VARCHAR2(2226 BYTE),
     ID_SAT_LINK_COASS VARCHAR2(2226 BYTE),
     NOM_COASSUREUR VARCHAR2(226 BYTE),
     TAUX_COASS FLOAT(126),
     STATUT VARCHAR2(226 BYTE)
 )


DROP TABLE LINK_COASS_ACCEPTATION ;
CREATE TABLE LINK_COASS_ACCEPTATION 
 ( 
   ---  ID_COASSUREUR  NUMBER,   
     ID_COASSURANCE VARCHAR2(255 BYTE),  
     ID_POLICE_AVENANT VARCHAR2(255 BYTE),
     ID_LINK_COASS_ACCEPTATION VARCHAR2(255 BYTE),
     DATE_INS  DATE,  
     DATE_FIN  DATE,       
     SOURCE    VARCHAR2(2226 BYTE)
    , STATUT         VARCHAR2(255 BYTE)
 )


DROP TABLE REASS_DB.SAT_LINK_COASS_ACCEPTATION;
CREATE TABLE REASS_DB.SAT_LINK_COASS_ACCEPTATION 
 ( 
    ID_COASSURANCE     VARCHAR2(255 BYTE),
  ID_POLICE_AVENANT  VARCHAR2(255 BYTE),
  DATE_INS           DATE,
  DATE_FIN             DATE, 
  SOURCE             VARCHAR2(255 BYTE),
  ID_SAT_LINK_COASS  VARCHAR2(255 BYTE),
  NOM_COASSUREUR     VARCHAR2(255 BYTE),
  TAUX_COASS         FLOAT(126),
  STATUT             VARCHAR2(255 BYTE)
 )



DROP TABLE REASS_DB.HUB_REASSURANCE ;
CREATE TABLE REASS_DB.HUB_REASSURANCE 

(
ID_REASSURANCE VARCHAR2(255 BYTE) NOT NULL,
DATE_INS           DATE,
SOURCE             VARCHAR2(2226 BYTE),
--MODEREASS       VARCHAR2(2226 BYTE), --FAC OU TRAITE
--TYPEREASS        VARCHAR2(2226 BYTE), --QUOTASHARE,EDP,XS,XL
--LIBEREASS      VARCHAR2(2226 BYTE),
CODEREASS      VARCHAR2(2226 BYTE)
);

DROP TABLE REASS_DB.SAT_REASSURANCE ;
CREATE TABLE REASS_DB.SAT_REASSURANCE 
(
ID_REASSURANCE VARCHAR2(255 BYTE) NOT NULL,
DATE_INS           DATE,
DATE_FIN           DATE,
SOURCE             VARCHAR2(2226 BYTE),
ID_SAT_REASSURANCE VARCHAR2(2226 BYTE) ,
CODEREASS      VARCHAR2(2226 BYTE),
LIBEREASS      VARCHAR2(2226 BYTE),
MODEREASS       VARCHAR2(2226 BYTE), --FAC OU TRAITE
TYPEREASS        VARCHAR2(2226 BYTE) --QUOTASHARE,EDP,XS,XL
 ,STATUT            VARCHAR2(255 BYTE)
);



DROP TABLE REASS_DB.SAT_TRAITE_REASSURANCE ;
CREATE TABLE REASS_DB.SAT_TRAITE_REASSURANCE 

(
ID_REASSURANCE VARCHAR2(255 BYTE) NOT NULL, --TYPE TRAITE UNIQUEMENT
DATE_INS           DATE,
DATE_FIN          DATE,
SOURCE             VARCHAR2(2226 BYTE),
ID_SAT_TRAITE_REASSURANCE   VARCHAR2(2226 BYTE) ,
 CODETRAITE             VARCHAR2(255 BYTE),
  LIBETRAITE             VARCHAR2(255 BYTE),
DATEEFFE           DATE,
DATEECHE           DATE
 ,STATUT            VARCHAR2(255 BYTE)
);


DROP TABLE REASS_DB.SAT_TRAITE_EDP ;
CREATE TABLE REASS_DB.SAT_TRAITE_EDP 

(
  ID_REASSURANCE VARCHAR2(255 BYTE) NOT NULL, --TYPE TRAITE UNIQUEMENT et MODE EDP UNIQUEMENT
  DATE_INS           DATE,
  DATE_FIN           DATE,
  SOURCE             VARCHAR2(2226 BYTE),
  ID_SAT_TRAITE_EDP VARCHAR2(2226 BYTE) ,
  LIBETRAITE             VARCHAR2(255 BYTE),
  PLEIN_CONSERVATION           FLOAT(126),
  NB_PLEIN                     FLOAT(126),
  ENGAGEMENT_REASSUREUR        FLOAT(126),
  CAPACITE_TRAITE        FLOAT(126)
   ,STATUT            VARCHAR2(255 BYTE)
);


DROP TABLE REASS_DB.SAT_TRAITE_XS ;
CREATE TABLE REASS_DB.SAT_TRAITE_XS 

(
ID_REASSURANCE               VARCHAR2(255 BYTE) NOT NULL, --TYPE TRAITE UNIQUEMENT et MODE XS UNIQUEMENT
DATE_INS                     DATE,
DATE_FIN                    DATE,
SOURCE                       VARCHAR2(2226 BYTE),
  ID_SAT_TRAITE_XS VARCHAR2(2226 BYTE) ,
  LIBETRAITE   VARCHAR2(255 BYTE),
PRIORITE                     FLOAT(126),
PORTEE                     FLOAT(126),
PLN_SCRPT                 FLOAT(126)
 ,STATUT            VARCHAR2(255 BYTE)
);
commit;
		
DROP TABLE REASS_DB.SAT_QUOTASHARE ;
CREATE TABLE REASS_DB.SAT_QUOTASHARE 
(
ID_REASSURANCE               VARCHAR2(255 BYTE) NOT NULL, --TYPE TRAITE et FAC et MODE QS UNIQUEMENT
DATE_INS                     DATE,
DATE_FIN                   DATE,
SOURCE                       VARCHAR2(2226 BYTE),
  ID_SAT_QUOTASHARE   VARCHAR2(2226 BYTE) ,
 CODEREASS VARCHAR2(255 BYTE),
 LIBEREASS  VARCHAR2(255 BYTE),
TAUX_CESSION                     FLOAT(126),
TAUX_COM                    FLOAT(126)
 ,STATUT            VARCHAR2(255 BYTE)
);

DROP TABLE REASS_DB.SAT_TRAITE_XL ;
CREATE TABLE REASS_DB.SAT_TRAITE_XL 
(
ID_REASSURANCE               VARCHAR2(255 BYTE) NOT NULL, --TYPE TRAITE UNIQUEMENT et MODE XL UNIQUEMENT
DATE_INS                     DATE,
DATE_FIN                   DATE,
SOURCE                       VARCHAR2(2226 BYTE),
ID_SAT_TRAITE_XL  VARCHAR2(2226 BYTE) 
 ,STATUT            VARCHAR2(255 BYTE)

);


DROP TABLE HUB_GARANTIE_CATALOGUE ;
CREATE TABLE HUB_GARANTIE_CATALOGUE 
(
ID_GARANTIE_CATALOGUE            VARCHAR2(255 BYTE) NOT NULL, 
DATE_INS                     DATE,
SOURCE                       VARCHAR2(2226 BYTE),
CODE_GARANTIE_CATALOGUE       VARCHAR2(2226 BYTE)

);

DROP TABLE REASS_DB.SAT_GARANTIE_CATALOGUE ;
CREATE TABLE REASS_DB.SAT_GARANTIE_CATALOGUE 
(
ID_GARANTIE_CATALOGUE               VARCHAR2(255 BYTE) NOT NULL, 
DATE_INS                     DATE,
SOURCE                       VARCHAR2(2226 BYTE),
  ID_SAT_GARANTIE_CATALOGUE NUMBER ,
CODE_GARANTIE_CATALOGUE       VARCHAR2(2226 BYTE),
CODEGARA                    VARCHAR2(2226 BYTE),
LIBEGARA                   VARCHAR2(2226 BYTE)
 ,STATUT            VARCHAR2(255 BYTE)
);

DROP TABLE LINK_TRAITE_GARANTIE_CATALOGUE ;
CREATE TABLE LINK_TRAITE_GARANTIE_CATALOGUE 
(
ID_GARANTIE_CATALOGUE               VARCHAR2(255 BYTE) NOT NULL, 
ID_REASSURANCE               VARCHAR2(255 BYTE) NOT NULL, --TYPE TRAITE UNIQUEMENT 
DATE_INS                     DATE,
SOURCE                       VARCHAR2(2226 BYTE)
  , STATUT         VARCHAR2(255 BYTE)
);


DROP TABLE REASS_DB.HUB_REASSUREUR CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.HUB_REASSUREUR
(
  ID_REASSUREUR VARCHAR2(255 BYTE)            NOT NULL,
  DATE_INS       DATE                           ,
  SOURCE         VARCHAR2(255 BYTE),
  CODE_REASSUREUR     VARCHAR2(255 BYTE)
);


DROP TABLE REASS_DB.SAT_REASSUREUR CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_REASSUREUR
(
  ID_REASSUREUR      VARCHAR2(255 BYTE)        NOT NULL,
  DATE_INS           DATE                       ,
  DATE_FIN                 DATE,
  SOURCE             VARCHAR2(255 BYTE),
  ID_SAT_REASSUREUR   VARCHAR2(255 BYTE),
  CODE_REASSUREUR         VARCHAR2(255 BYTE),
  LIBELLE_REASSUREUR      VARCHAR2(255 BYTE)
   ,STATUT            VARCHAR2(255 BYTE)
)
;
DROP TABLE REASS_DB.LINK_REASSURANCE_REASSUREUR ;
CREATE TABLE REASS_DB.LINK_REASSURANCE_REASSUREUR 
(
ID_REASSURANCE               VARCHAR2(255 BYTE) , 
ID_REASSUREUR                VARCHAR2(255 BYTE) , 
ID_LINK_REASSURANCE_REASSUREUR               VARCHAR2(255 BYTE) , 
CODEREASS                    VARCHAR2(2226 BYTE),
REASSUR                   VARCHAR2(255 BYTE),
DATE_INS                     DATE,
DATE_FIN                     DATE,
SOURCE                       VARCHAR2(255 BYTE)
  , STATUT         VARCHAR2(255 BYTE)
);


DROP TABLE LINK_REASSURANCE_GARANTIE ;
CREATE TABLE LINK_REASSURANCE_GARANTIE 
(
ID_GARANTIE               VARCHAR2(255 BYTE) ,--NOT NULL, 
ID_REASSURANCE               VARCHAR2(255 BYTE), --NOT NULL, 
ID_LINK_REASSURANCE_GARANTIE   VARCHAR2(255 BYTE) , 
DATE_INS                     DATE,
DATE_FIN                   DATE,
SOURCE                       VARCHAR2(2226 BYTE)
  , STATUT         VARCHAR2(255 BYTE)
);



commit;
DROP TABLE REASS_DB.SAT_LINK_REASS_REASSUREUR ;
CREATE TABLE REASS_DB.SAT_LINK_REASS_REASSUREUR 
(
ID_REASSURANCE               VARCHAR2(255 BYTE) NOT NULL, 
ID_REASSUREUR               VARCHAR2(255 BYTE) NOT NULL, 
DATE_INS                     DATE,
DATE_FIN                 DATE,
SOURCE                       VARCHAR2(2226 BYTE),
  ID_SAT_LINK_REASS_REASSUREUR  VARCHAR2(2226 BYTE) ,
 CODEREASS  VARCHAR2(255 BYTE),
 --LIBEREASS  VARCHAR2(255 BYTE),
TAUX_COM_REASSURANCE         FLOAT(126),
PART_REASSUREUR             FLOAT(126)
 ,STATUT            VARCHAR2(255 BYTE)
);

DROP TABLE HUB_BRANCHE_CIMA ;
CREATE TABLE HUB_BRANCHE_CIMA 
(
ID_BRANCHE                  VARCHAR2(255 BYTE) NOT NULL, 
DATE_INS                     DATE,
SOURCE                       VARCHAR2(2226 BYTE),
CODEBRAN                    VARCHAR2(2226 BYTE)

);


DROP TABLE REASS_DB.SAT_BRANCHE_CIMA ;
CREATE TABLE REASS_DB.SAT_BRANCHE_CIMA 
(
ID_BRANCHE                  VARCHAR2(255 BYTE) NOT NULL, 
DATE_INS                     DATE,
DATE_FIN                 DATE,
SOURCE                       VARCHAR2(2226 BYTE),
ID_SAT_BRANCHE     VARCHAR2(2226 BYTE),
CODEBRAN                    VARCHAR2(2226 BYTE),
LIBEBRAN                    VARCHAR2(2226 BYTE)
);

DROP TABLE LINK_BRANCHE_GAR_CATALOGUE ;
CREATE TABLE LINK_BRANCHE_GAR_CATALOGUE 
(
ID_GARANTIE_CATALOGUE       VARCHAR2(255 BYTE) NOT NULL, 
ID_BRANCHE                  VARCHAR2(255 BYTE) NOT NULL,
SOURCE                       VARCHAR2(2226 BYTE)
  , STATUT         VARCHAR2(255 BYTE)
);

DROP TABLE LINK_REASSURANCE_GARANTIE ;
CREATE TABLE LINK_REASSURANCE_GARANTIE 
(
ID_GARANTIE               VARCHAR2(255 BYTE) , 
ID_REASSURANCE                 VARCHAR2(255 BYTE) , 
DATE_INS                     DATE,
SOURCE                       VARCHAR2(2226 BYTE)
  , STATUT         VARCHAR2(255 BYTE)
);

DROP TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_FAC ;
CREATE TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_FAC 
(
ID_GARANTIE                  VARCHAR2(255 BYTE) NOT NULL, 
ID_REASSURANCE                 VARCHAR2(255 BYTE) NOT NULL, --MODE FAC
DATE_INS                     DATE,
DATE_FIN                 DATE,
SOURCE                       VARCHAR2(2226 BYTE),
ID_SAT_LINK_REASS_GARANTIE_FAC     VARCHAR2(2226 BYTE),
CAPITAUX_AVANT_FAC           FLOAT(126),
PRIME_AVANT_FAC              FLOAT(126),
TAUX_CESSION                 FLOAT(126),
CAPITAUX_CEDES               FLOAT(126),
PRIME_CEDEE                  FLOAT(126),
CAPITAUX_APRES_FAC           FLOAT(126),
PRIME_APRES_FAC              FLOAT(126)
 ,STATUT            VARCHAR2(255 BYTE)
);



DROP TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_EDP ;
CREATE TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_EDP 
(
ID_GARANTIE                  VARCHAR2(255 BYTE) NOT NULL, 
ID_REASSURANCE                 VARCHAR2(255 BYTE) NOT NULL, --MODE TRAITE, TYPE ; EDP
DATE_INS                     DATE,
DATE_FIN                 DATE,
SOURCE                       VARCHAR2(2226 BYTE),
ID_SAT_LINK_REASS_GARANTIE_EDP    VARCHAR2(2226 BYTE),
CAPITAUX_AVANT_EDP           FLOAT(126),
PRIME_AVANT_EDP              FLOAT(126),
TAUX_CESSION                 FLOAT(126),
RETENTION                    FLOAT(126),
PLEIN_CONSERVATION           FLOAT(126),
NB_PLEIN                     FLOAT(126),
CAPITAUX_CEDES               FLOAT(126),
PRIME_CEDEE                  FLOAT(126),
CAPITAUX_APRES_EDP           FLOAT(126),
PRIME_APRES_EDP              FLOAT(126),
CAPITAUX_DECOUVERT           FLOAT(126),
PRIME_DECOUVERT              FLOAT(126)
 ,STATUT            VARCHAR2(255 BYTE)
);


DROP TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_CL ;
CREATE TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_CL
(
ID_GARANTIE                  VARCHAR2(255 BYTE) NOT NULL, 
ID_REASSURANCE                 VARCHAR2(255 BYTE) NOT NULL, --MODE TRAITE, TYPE ; EDP
DATE_INS                     DATE,
DATE_FIN                 DATE,
SOURCE                       VARCHAR2(2226 BYTE),
ID_SAT_LINK_REASS_GARANTIE_CL    VARCHAR2(2226 BYTE),
CAPITAUX_AVANT_CL          FLOAT(126),
PRIME_AVANT_CL              FLOAT(126),
TAUX_CL                 FLOAT(126),

CAPITAUX_CEDES               FLOAT(126),
PRIME_CEDEE                  FLOAT(126),

CAPITAUX_APRES_CL          FLOAT(126),
PRIME_APRES_CL            FLOAT(126)
 ,STATUT            VARCHAR2(255 BYTE)
);

DROP TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_XS ;
CREATE TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_XS
(
ID_GARANTIE                  VARCHAR2(255 BYTE) NOT NULL, 
ID_REASSURANCE                 VARCHAR2(255 BYTE) NOT NULL, --MODE TRAITE, TYPE ; XS
DATE_INS                     DATE,
DATE_FIN                 DATE,
SOURCE                       VARCHAR2(2226 BYTE),
ID_SAT_LINK_REASS_GARANTIE_XS   VARCHAR2(2226 BYTE),
CAPITAUX_RETENUS         FLOAT(126),
PRIME_RETENUE             FLOAT(126)
 ,STATUT            VARCHAR2(255 BYTE)
);

DROP TABLE REASS_DB.INPUT_CL CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.INPUT_CL
(
    ID_GARANTIE       VARCHAR2(255 BYTE)      
    ,ID_REASSURANCE    VARCHAR2(255 BYTE)      
    ,ID_POLICE_AVENANT VARCHAR2(255 BYTE)
    --
    --,DATE_INS          DATE
    --,DATE_FIN          DATE
    --     
    ,CODEINTE          VARCHAR2(255 BYTE) 
    ,NUMEPOLI          VARCHAR2(255 BYTE) 
    ,NUMEAVEN          VARCHAR2(255 BYTE) 
    ,CAPITAUX          FLOAT(126)
    ,SMP               FLOAT(126)
    ,PRM_NT            FLOAT(126)
    --changer TAUX_CESSION en TAUX_CL
    --,TAUX_CL         FLOAT(126)
    ,TAUX_CESSION      FLOAT(126) 
    ,TAUX_COASS        FLOAT(126)
);


DROP TABLE REASS_DB.INPUT_FAC CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.INPUT_FAC
(
  ID_GARANTIE VARCHAR2(255 BYTE)  
  ,ID_REASSURANCE VARCHAR2(255 BYTE)
  --,DATE_INS        FLOAT(126)
  --,DATE_FIN        FLOAT(126)
  --,i.ID_POLICE_AVENANT
  ,CODEINTE VARCHAR2(255 BYTE)
  ,NUMEPOLI VARCHAR2(255 BYTE)
  ,NUMEAVEN VARCHAR2(255 BYTE)
  ,CAPITAUX  FLOAT(126)
  ,SMP      FLOAT(126)
  ,PRM_NT   FLOAT(126)
  ,TAUX_FAC  FLOAT(126)
  ,TAUX_COM  FLOAT(126)
  --,TAUX_CL    FLOAT(126)
  --,TAUX_COASS FLOAT(126)
  --,STATUT_COASS VARCHAR2(255 BYTE)

)


DROP TABLE REASS_DB.INPUT_EDP CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.INPUT_EDP
(
    ID_GARANTIE       VARCHAR2(255 BYTE)      
    ,ID_REASSURANCE    VARCHAR2(255 BYTE)      
    ,ID_POLICE_AVENANT VARCHAR2(255 BYTE)
    --,DATE_INS          DATE
    --,DATE_FIN          DATE
    ,CODEINTE          VARCHAR2(255 BYTE)
    ,NUMEPOLI          VARCHAR2(255 BYTE)
    ,NUMEAVEN          VARCHAR2(255 BYTE)
    ,CAPITAUX          FLOAT(126)
    ,SMP               FLOAT(126)
    ,PRM_NT            FLOAT(126)
    ,TAUX_CL           FLOAT(126) 
    ,TAUX_FAC          FLOAT(126) 
    ,TAUX_COASS        FLOAT(126)
    --,STATUT_COASS      FLOAT(126)     
    --,CLASS_RISQ        FLOAT(126)
    ,PRCT_RED_CPCT        FLOAT(126)
    ,PLEIN_CONSERVATION      FLOAT(126) 
    ,NB_PLEIN          FLOAT(126) 
    ,ENGAGEMENT_REASSUREUR        FLOAT(126)
    ,CAPACITE_TRAITE  FLOAT(126)
);

--create table GARANTIES_BKP as (select*from REASS_DB.GARANTIES);


---DROP TABLE REASS_DB.HUB_POLICE_AVENANT CASCADE CONSTRAINTS;
---
---CREATE TABLE REASS_DB.HUB_POLICE_AVENANT
---(
---  ID_POLICE_AVENANT  NUMBER,
---  DATE_INS           DATE,
---  SOURCE             VARCHAR2(2226 BYTE),
---  CODEINTE           INTEGER,
---  NUMEPOLI           FLOAT(126),
---  NUMEAVEN           INTEGER,
---  STATUT
---)


DROP TABLE REASS_DB.SAT_COASSUREUR CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_COASSUREUR
(
  ID_COASSUREUR      VARCHAR2(1000 BYTE)        NOT NULL,
  DATE_INS           DATE                       DEFAULT SYSDATE,
  DATE_FIN                 DATE,
  SOURCE             VARCHAR2(255 BYTE),
  ID_SAT_COASSUREUR  VARCHAR2(255 BYTE),
  CODE_COASS         VARCHAR2(255 BYTE),
  NOM_COASSUREUR     VARCHAR2(255 BYTE),
  STATUT     VARCHAR2(255 BYTE)
);

DROP TABLE REASS_DB.SAT_LINK_REASS_GARA_CL CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_LINK_REASS_GARA_CL
(
  ID_GARANTIE                VARCHAR2(255 BYTE)             NOT NULL,
  ID_REASSURANCE             VARCHAR2(255 BYTE)             NOT NULL,
  DATE_INS                   DATE,
  DATE_FIN                  DATE,
  SOURCE                     VARCHAR2(255 BYTE),
  ID_SAT_LINK_REASS_GARA_CL  VARCHAR2(255 BYTE),
  CODEINTE                   INTEGER,
  NUMEPOLI                   FLOAT(126),
  NUMEAVEN                   INTEGER,
  TAUX_CESSION               FLOAT(126),
  STATUT                     VARCHAR2(255 BYTE)
);
commit;


CREATE TABLE REASS_DB.GARANTIES
(
  NUMEPOLI           FLOAT(126),
  CODEINTE           INTEGER,
  NUMEAVEN           INTEGER,
  DATECOMP           VARCHAR2(255 BYTE),
  DATEEFFE           VARCHAR2(255 BYTE),
  DATEECHE           VARCHAR2(255 BYTE),
  CODECATE           INTEGER,
  LIBECATE           VARCHAR2(255 BYTE),
  CODEBRAN           INTEGER,
  LIBEBRAN           VARCHAR2(255 BYTE),
  CODEGARA           VARCHAR2(255 BYTE),
  LIBEL_BRAN_RE      VARCHAR2(255 BYTE),
  CODERISQ           INTEGER,
  LIBERISQ           VARCHAR2(255 BYTE),
  CLASS_RISQ         VARCHAR2(255 BYTE),
  LIBECLASS          VARCHAR2(255 BYTE),
  CAPITAUX           FLOAT(126),
  SMP                FLOAT(126),
  PRM_NT             FLOAT(126),
  CODE_GARANTIE_REF  VARCHAR2(255 BYTE)
);

DROP TABLE REASS_DB.OUTPUT_CL CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.OUTPUT_CL
(
  ID_GARANTIE                    VARCHAR2(255 BYTE),
  ID_REASSURANCE                 VARCHAR2(255 BYTE),
  ID_SAT_LINK_REASS_GARANTIE_CL  VARCHAR2(255 BYTE),
  CAPITAUX_AVANT_CL              FLOAT(126),
  PRIME_AVANT_CL                 FLOAT(126),
  TAUX_CL                        FLOAT(126),
  CAPITAUX_CEDES                 FLOAT(126),
  PRIME_CEDEE                    FLOAT(126),
  CAPITAUX_APRES_CL              FLOAT(126),
  PRIME_APRES_CL                 FLOAT(126),
  STATUT                         VARCHAR2(255 BYTE)
);

DROP TABLE REASS_DB.HUB_COASSURANCE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.HUB_COASSURANCE
(
  ID_COASSURANCE  VARCHAR2(4000 BYTE),
  CODEINTE        VARCHAR2(255 BYTE),
  NUMEPOLI        VARCHAR2(255 BYTE),
  NUMEAVEN        VARCHAR2(255 BYTE),
  NOM_COASR       VARCHAR2(255 BYTE),
  DATE_INS        DATE,
  SOURCE          VARCHAR2(255  BYTE)
);
commit;

DROP TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_EDP CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_EDP
(
  ID_GARANTIE                     VARCHAR2(255 BYTE) NOT NULL,
  ID_REASSURANCE                  VARCHAR2(255 BYTE) NOT NULL,
  DATE_INS                        DATE,
  DATE_FIN                        DATE,
  SOURCE                          VARCHAR2(2226 BYTE),
  ID_SAT_LINK_REASS_GARANTIE_EDP  VARCHAR2(2226 BYTE),
  CAPITAUX_AVANT_EDP              FLOAT(126),
  PRIME_AVANT_EDP                 FLOAT(126),
  TAUX_CESSION                    FLOAT(126),
  CAPITAUX_RETENTION                       FLOAT(126),
  PRIME_RETENTION                       FLOAT(126),
  PLEIN_CONSERVATION              FLOAT(126),
  NB_PLEIN                        FLOAT(126),
  CAPITAUX_CEDES                  FLOAT(126),
  PRIME_CEDEE                     FLOAT(126),
  CAPITAUX_APRES_EDP              FLOAT(126),
  PRIME_APRES_EDP                 FLOAT(126),
  CAPITAUX_DECOUVERT              FLOAT(126),
  PRIME_DECOUVERT                 FLOAT(126),
  STATUT                          VARCHAR2(255 BYTE)
)
;
DROP TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_FAC CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_FAC
(
  ID_GARANTIE                     VARCHAR2(255 BYTE) NOT NULL,
  ID_REASSURANCE                  VARCHAR2(255 BYTE) NOT NULL,
  DATE_INS                        DATE,
  DATE_FIN                        DATE,
  SOURCE                          VARCHAR2(2226 BYTE),
  ID_SAT_LINK_REASS_GARANTIE_FAC  VARCHAR2(2226 BYTE),
  --CAPITAUX_AVANT_FAC              FLOAT(126),
  --PRIME_AVANT_FAC                 FLOAT(126),
  TAUX_CESSION                    FLOAT(126),
  CAPITAUX_CEDES                  FLOAT(126),
  PRIME_CEDEE                     FLOAT(126),
  CAPITAUX_APRES_FAC              FLOAT(126),
  PRIME_APRES_FAC                 FLOAT(126),
  STATUT                          VARCHAR2(255 BYTE)
)
;
commit;

--creation des tables sat_link_reass_garantie

DROP TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_CL;
CREATE TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_CL 
(
    ID_GARANTIE VARCHAR2(255 BYTE),
    ID_REASSURANCE VARCHAR2(255 BYTE),
    DATE_INS DATE,
    DATE_FIN DATE,
    SOURCE VARCHAR2(255 BYTE),
    ID_SAT_LINK_REASS_GARANTIE_CL VARCHAR2(255 BYTE),
    CAPITAUX_AVANT_CL FLOAT(126),
    SMP_AVANT_CL FLOAT(126),
    PRIME_AVANT_CL FLOAT(126),
    TAUX_CL FLOAT(126),
    CAPITAUX_CEDES_CL FLOAT(126),
    SMP_CEDE_CL FLOAT(126),
    PRIME_CEDEE_CL FLOAT(126),
    CAPITAUX_APRES_CL FLOAT(126),
    SMP_APRES_CL FLOAT(126),
    PRIME_APRES_CL FLOAT(126),
    STATUT VARCHAR2(255 BYTE)
);

DROP TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_FAC;
CREATE TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_FAC 
(
    ID_GARANTIE VARCHAR2(255 BYTE),
    ID_REASSURANCE VARCHAR2(255 BYTE),
    DATE_INS DATE,
    DATE_FIN DATE,
    SOURCE VARCHAR2(255 BYTE),
    ID_SAT_LINK_REASS_GARANTIE_FAC VARCHAR2(255 BYTE),
    CAPITAUX_AVANT_FAC FLOAT(126),
    SMP_AVANT_FAC FLOAT(126),
    PRIME_AVANT_FAC FLOAT(126),
    TAUX_FAC FLOAT(126),
    CAPITAUX_CEDES_FAC FLOAT(126),
    SMP_CEDE_FAC FLOAT(126),
    PRIME_CEDEE_FAC FLOAT(126),
    CAPITAUX_APRES_FAC FLOAT(126),
    SMP_APRES_FAC FLOAT(126),
    PRIME_APRES_FAC FLOAT(126),
    STATUT VARCHAR2(255 BYTE)
);

DROP TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_EDP;
CREATE TABLE REASS_DB.SAT_LINK_REASS_GARANTIE_EDP 
(
    ID_GARANTIE VARCHAR2(255 BYTE),
    ID_REASSURANCE VARCHAR2(255 BYTE),
    DATE_INS DATE,
    DATE_FIN DATE,
    SOURCE VARCHAR2(255 BYTE),
    ID_SAT_LINK_REASS_GARANTIE_EDP VARCHAR2(255 BYTE),
    CAPITAUX_AVANT_EDP FLOAT(126),
    SMP_AVANT_EDP FLOAT(126),
    PRIME_AVANT_EDP FLOAT(126),
    PRCT_RED_CPCT FLOAT(126),
    PLEIN_CONSERVATION FLOAT(126),
    NB_PLEIN FLOAT(126),
    ENGAGEMENT_REASSUREUR FLOAT(126),
    CAPACITE_TRAITE FLOAT(126),
    TAUX_EDP FLOAT(126),
    CAPIATAUX_CEDE_EDP FLOAT(126),
    SMP_CEDE_EDP FLOAT(126),
    PRIME_CEDEE_EDP FLOAT(126),
    CAPITAUX_APRES_EDP FLOAT(126),
    SMP_APRES_EDP FLOAT(126),
    PRIME_APRES_EDP FLOAT(126),
    CAPITAUX_RETENTION FLOAT(126),
    SMP_RETENTION FLOAT(126),
    PRIME_RETENTION FLOAT(126),
    TAUX_RETENTION FLOAT(126),
    CAPITAUX_DECOUVERT FLOAT(126),
    SMP_DECOUVERT FLOAT(126),
    PRIME_DECOUVERT FLOAT(126),
    STATUT VARCHAR2(255 BYTE)
);

--creation des tables temp

DROP TABLE REASS_DB.TEMP_CL;
CREATE TABLE REASS_DB.TEMP_CL
(
    ID_GARANTIE VARCHAR2(255 BYTE),
    ID_REASSURANCE VARCHAR2(255 BYTE),
    DATE_INS DATE,
    DATE_FIN DATE,
    SOURCE VARCHAR2(255 BYTE),
    ID_SAT_LINK_REASS_GARANTIE_CL VARCHAR2(255 BYTE),
    CAPITAUX_AVANT_CL FLOAT(126),
    SMP_AVANT_CL FLOAT(126),
    PRIME_AVANT_CL FLOAT(126),
    TAUX_CL FLOAT(126),
    CAPITAUX_CEDES_CL FLOAT(126),
    SMP_CEDE_CL FLOAT(126),
    PRIME_CEDEE_CL FLOAT(126),
    CAPITAUX_APRES_CL FLOAT(126),
    SMP_APRES_CL FLOAT(126),
    PRIME_APRES_CL FLOAT(126),
    STATUT VARCHAR2(255 BYTE)
);

DROP TABLE REASS_DB.TEMP_FAC;
CREATE TABLE REASS_DB.TEMP_FAC
(
    ID_GARANTIE VARCHAR2(255 BYTE),
    ID_REASSURANCE VARCHAR2(255 BYTE),
    DATE_INS DATE,
    DATE_FIN DATE,
    SOURCE VARCHAR2(255 BYTE),
    ID_SAT_LINK_REASS_GARANTIE_FAC VARCHAR2(255 BYTE),
    CAPITAUX_AVANT_FAC FLOAT(126),
    SMP_AVANT_FAC FLOAT(126),
    PRIME_AVANT_FAC FLOAT(126),
    TAUX_FAC FLOAT(126),
    CAPITAUX_CEDES_FAC FLOAT(126),
    SMP_CEDE_FAC FLOAT(126),
    PRIME_CEDEE_FAC FLOAT(126),
    CAPITAUX_APRES_FAC FLOAT(126),
    SMP_APRES_FAC FLOAT(126),
    PRIME_APRES_FAC FLOAT(126),
    STATUT VARCHAR2(255 BYTE)
);

DROP TABLE REASS_DB.TEMP_EDP;
CREATE TABLE REASS_DB.TEMP_EDP
(
    ID_GARANTIE VARCHAR2(255 BYTE),
    ID_REASSURANCE VARCHAR2(255 BYTE),
    DATE_INS DATE,
    DATE_FIN DATE,
    SOURCE VARCHAR2(255 BYTE),
    ID_SAT_LINK_REASS_GARANTIE_EDP VARCHAR2(255 BYTE),
    CAPITAUX_AVANT_EDP FLOAT(126),
    SMP_AVANT_EDP FLOAT(126),
    PRIME_AVANT_EDP FLOAT(126),
    PRCT_RED_CPCT FLOAT(126),
    PLEIN_CONSERVATION FLOAT(126),
    NB_PLEIN FLOAT(126),
    ENGAGEMENT_REASSUREUR FLOAT(126),
    CAPACITE_TRAITE FLOAT(126),
    TAUX_EDP FLOAT(126),
    CAPIATAUX_CEDE_EDP FLOAT(126),
    SMP_CEDE_EDP FLOAT(126),
    PRIME_CEDEE_EDP FLOAT(126),
    CAPITAUX_APRES_EDP FLOAT(126),
    SMP_APRES_EDP FLOAT(126),
    PRIME_APRES_EDP FLOAT(126),
    CAPITAUX_RETENTION FLOAT(126),
    SMP_RETENTION FLOAT(126),
    PRIME_RETENTION FLOAT(126),
    TAUX_RETENTION FLOAT(126),
    CAPITAUX_DECOUVERT FLOAT(126),
    SMP_DECOUVERT FLOAT(126),
    PRIME_DECOUVERT FLOAT(126),
    STATUT VARCHAR2(255 BYTE)
);

-- creation des tables temp_input

DROP TABLE REASS_DB.TEMP_INPUT_CL;
CREATE TABLE REASS_DB.TEMP_INPUT_CL
(
    ID_GARANTIE VARCHAR2(255 BYTE),
    ID_REASSURANCE VARCHAR2(255 BYTE),
    ID_POLICE_AVENANT VARCHAR2(255 BYTE),
    CODEINTE VARCHAR2(255 BYTE),
    NUMEPOLI VARCHAR2(255 BYTE),
    NUMEAVEN VARCHAR2(255 BYTE),
    CAPITAUX FLOAT(126),
    SMP FLOAT(126),
    PRM_NT FLOAT(126),
    TAUX_CL FLOAT(126),
    TAUX_COASS FLOAT(126),
    STATUT_COASS VARCHAR2(255 BYTE)
);

DROP TABLE REASS_DB.TEMP_INPUT_FAC;
CREATE TABLE REASS_DB.TEMP_INPUT_FAC
(
    ID_GARANTIE VARCHAR2(255 BYTE),
    ID_REASSURANCE VARCHAR2(255 BYTE),
    CODEINTE VARCHAR2(255 BYTE),
    NUMEPOLI VARCHAR2(255 BYTE),
    NUMEAVEN VARCHAR2(255 BYTE),
    CAPITAUX FLOAT(126),
    SMP FLOAT(126),
    PRM_NT FLOAT(126),
    TAUX_FAC FLOAT(126),
    TAUX_COM FLOAT(126)
);

DROP TABLE REASS_DB.TEMP_INPUT_EDP;
CREATE TABLE REASS_DB.TEMP_INPUT_EDP
(
    ID_GARANTIE VARCHAR2(255 BYTE),
    ID_REASSURANCE VARCHAR2(255 BYTE),
    ID_POLICE_AVENANT VARCHAR2(255 BYTE),
    CODEINTE VARCHAR2(255 BYTE),
    NUMEPOLI VARCHAR2(255 BYTE),
    NUMEAVEN VARCHAR2(255 BYTE),
    CAPITAUX FLOAT(126),
    SMP FLOAT(126),
    PRM_NT FLOAT(126),
    TAUX_CL FLOAT(126),
    TAUX_FAC FLOAT(126),
    TAUX_COASS FLOAT(126),
    STATUT_COASS VARCHAR2(255 BYTE),
    CLASS_RISQ VARCHAR2(255 BYTE),
    PRCT_RED_CPCT FLOAT(126),
    PLEIN_CONSERVATION FLOAT(126),
    NB_PLEIN FLOAT(126),
    ENGAGEMENT_REASSUREUR FLOAT(126),
    CAPACITE_TRAITE FLOAT(126)
);

DROP TABLE REASS_DB.SAT_OUTPUT_REASS CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_OUTPUT_REASS
(
  ID_GARANTIE          VARCHAR2(255 BYTE),
   ID_REASSURANCE_CL  VARCHAR2(255 BYTE),
   ID_REASSURANCE_FAC VARCHAR2(255 BYTE),
   ID_REASSURANCE_EDP VARCHAR2(255 BYTE),
   
  DATE_INS             DATE,
  DATE_FIN             DATE,
  SOURCE               VARCHAR2(255 BYTE),
  ID_SAT_OUTPUT_REASS  VARCHAR2(255 BYTE),
  CODEINTE              VARCHAR2(255 BYTE),
  NUMEPOLI              VARCHAR2(255 BYTE),
  NUMEAVEN              VARCHAR2(255 BYTE),
  DATEEFFE              VARCHAR2(255 BYTE),
  DATEECHE              VARCHAR2(255 BYTE),
  CODECATE              INTEGER,
  LIBECATE              VARCHAR2(255 BYTE),
  CODEBRAN              INTEGER,
  LIBEBRAN              VARCHAR2(255 BYTE),
  CODEGARA              VARCHAR2(255 BYTE),
  LIBEL_BRAN_RE         VARCHAR2(255 BYTE),
  LIBERISQ              VARCHAR2(255 BYTE),
  CODERISQ              INTEGER,
  LIBECLASS             VARCHAR2(255 BYTE),
  CLASS_RISQ            VARCHAR2(255 BYTE),
  ACTIVITE              VARCHAR2(255 BYTE),
  CODEASSU              VARCHAR2(255 BYTE),
  NOM                   VARCHAR2(255 BYTE),
  CAPITAUX_100          NUMBER,
  SMP_100               NUMBER,
  PRM_NT_100            NUMBER,
  TAUX_COASS            NUMBER,
  CAPITAUX_NET_COASS    NUMBER,
  SMP_NET_COASS         NUMBER,
  PRIME_NET_COASS       NUMBER,
  PRIME_REVERSEE_COASS  NUMBER,
 CAPITAUX_AVANT_CL      float(126),
 SMP_AVANT_CL           float(126),
 PRIME_AVANT_CL         float(126),
 TAUX_CL                float(126),
 CAPITAUX_CEDES_CL      float(126),
 SMP_CEDE_CL            float(126),
 PRIME_CEDEE_CL         float(126),
 CAPITAUX_APRES_CL      float(126),
 SMP_APRES_CL           float(126),
 PRIME_APRES_CL         float(126),
 CAPITAUX_AVANT_FAC     float(126),
 SMP_AVANT_FAC        float(126),
 PRIME_AVANT_FAC        float(126),
 TAUX_FAC               float(126),
 CAPITAUX_CEDES_FAC     float(126),
 SMP_CEDE_FAC           float(126),
 PRIME_CEDEE_FAC        float(126),
 CAPITAUX_APRES_FAC     float(126),
 SMP_APRES_FAC          float(126),
 PRIME_APRES_FAC        float(126),
 
 CAPITAUX_AVANT_EDP     float(126),
 SMP_AVANT_EDP          float(126),
 PRIME_AVANT_EDP        float(126),
 PRCT_RED_CPCT          float(126),
 PLEIN_CONSERVATION     float(126),
 NB_PLEIN               float(126),
 ENGAGEMENT_REASSUR     float(126),
 CAPACITE_TRAITE        float(126),
 TAUX_EDP               float(126),
 CAPITAUX_CEDE_EDP      float(126),
 SMP_CEDE_EDP           float(126),
 PRIME_CEDEE_EDP        float(126),
 CAPITAUX_APRES_EDP     float(126),
 SMP_APRES_EDP          float(126),
 PRIME_APRES_EDP        float(126),
 CAPITAUX_RETENTION     float(126),
 SMP_RETENTION          float(126),
 PRIME_RETENTION        float(126),
 TAUX_RETENTION         float(126),
 CAPITAUX_DECOUVERT     float(126),
 SMP_DECOUVERT          float(126),
 PRIME_DECOUVERT        float(126),
 STATUT                 Varchar2(226 BYTE)
)

DROP TABLE REASS_DB.SAT_PRIME CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_PRIME
(
  ID_GARANTIE           VARCHAR2(255 BYTE),
  DATE_INS              DATE,
  DATE_FIN              DATE,
  SOURCE                VARCHAR2(255 BYTE),
  ID_SAT_PRIME          VARCHAR2(4000 BYTE),
  CODEINTE              VARCHAR2(255 BYTE),
  NUMEPOLI              VARCHAR2(255 BYTE),
  NUMEAVEN              VARCHAR2(255 BYTE),
  CODEGARA              VARCHAR2(255 BYTE),
  LIBEL_BRAN_RE         VARCHAR2(50 BYTE),
  CODERISQ              VARCHAR2(255 BYTE),
  STATUT_COASS          VARCHAR2(10 BYTE),
  TAUX_COASS            NUMBER,
  PRM_NT                NUMBER,
  PRIME_NET_COASS       NUMBER,
  PRIME_REVERSEE_COASS  NUMBER,
  STATUT                VARCHAR2(255 BYTE)
)

;DROP TABLE REASS_DB.REPORTING_REASS_M_POLICE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.REPORTING_REASS_M_POLICE
(
  CODEBRAN         NUMBER,
  CODEINTE         VARCHAR2(255 BYTE),
  NUMEPOLI         VARCHAR2(255 BYTE),
  NUMEAVEN         VARCHAR2(255 BYTE),
  STATUT_TRAITE    NUMBER,
  --STATUT_MILLIARD    NUMBER,
 -- STATUT_NOS_CALCULS    NUMBER,
  DATEEFFE         VARCHAR2(255 BYTE),
  DATEECHE         VARCHAR2(255 BYTE),
  DATECOMP         VARCHAR2(255 BYTE),
  SOURCE           VARCHAR2(255 BYTE),
  LIBEREASS        VARCHAR2(2226 BYTE),
  REASS            VARCHAR2(226 BYTE),
  TAUX             NUMBER,
  PRIME_CEDEE      NUMBER,
  PRM_NT_100       NUMBER,
  PRIME_DECOUVERT  NUMBER,
  PRIME_RETENTION  NUMBER,
  STATUT           VARCHAR2(226 BYTE)
)

;

DROP TABLE REASS_DB.REPORTING_REASS_M_BRANCHE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.REPORTING_REASS_M_BRANCHE
(
  CODEBRAN         NUMBER,
  CODEINTE         VARCHAR2(255 BYTE),
  NUMEPOLI         VARCHAR2(255 BYTE),
  NUMEAVEN         VARCHAR2(255 BYTE),
  ANNEE_EFFET      VARCHAR2(4 BYTE),
  STATUT_TRAITE    NUMBER,
  STATUT_NOS_CALCULS    NUMBER,
  STATUT_MILLIARD    NUMBER,
  SOURCE           VARCHAR2(255 BYTE),
  STATUT_COASS     VARCHAR2(10 BYTE),
  STATUT           CHAR(16 BYTE),
  PRM_NT_100       NUMBER,
  PRM_NT_COASS     NUMBER,
  PRIME_CEDEE_CL   NUMBER,
  PRIME_CEDEE_FAC  NUMBER,
  PRIME_CEDEE_EDP  NUMBER,
  PRIME_DECOUVERT  NUMBER,
  PRIME_RETENTION  NUMBER
)
;
DROP TABLE REASS_DB.HUB_SINISTRE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.HUB_SINISTRE  

(
  ID_SINISTRE  VARCHAR2(255 BYTE),
  DATE_INS      DATE,
  --DATE_FIN       DATE,
  SOURCE         VARCHAR2(255 BYTE),
  ANNEE             NUMBER,
  CODEINTE         VARCHAR2(255 BYTE),
  NUMESINI         VARCHAR2(255 BYTE)


)
;
DROP TABLE REASS_DB.SAT_SINISTRE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_SINISTRE  

(
  ID_SINISTRE      VARCHAR2(255 BYTE),
  DATE_INS         DATE,
  DATE_FIN         DATE,
  SOURCE           VARCHAR2(255 BYTE),
  ID_SAT_SINISTRE  VARCHAR2(255 BYTE),
  ANNEE            NUMBER,
  CODEINTE         VARCHAR2(255 BYTE),
  NUMESINI         VARCHAR2(255 BYTE),
  NATUSINI         VARCHAR2(255 BYTE),
  STATUT         VARCHAR2(255 BYTE)
)

;


DROP TABLE REASS_DB.LINK_SINISTRE_GARANTIE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.LINK_SINISTRE_GARANTIE  

(
  ID_SINISTRE      VARCHAR2(255 BYTE),
  ID_GARANTIE     VARCHAR2(255 BYTE),
  DATE_INS         DATE,
  DATE_FIN         DATE,
  SOURCE           VARCHAR2(255 BYTE),
  ID_LINK_SINISTRE_GARANTIE  VARCHAR2(255 BYTE),
  ANNEE            NUMBER,
  CODEINTE         VARCHAR2(255 BYTE),
  NUMESINI         VARCHAR2(255 BYTE),
  NATUSINI         VARCHAR2(255 BYTE),
  NUMEPOLI        VARCHAR2(255 BYTE),
  NUMEAVEN         VARCHAR2(255 BYTE),
  CODERISQ         VARCHAR2(255 BYTE),
  CODEGARA        VARCHAR2(255 BYTE),
  STATUT         VARCHAR2(255 BYTE)
)
;


DROP TABLE REASS_DB.SAT_LINK_SINISTRE_GARANTIE CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.SAT_LINK_SINISTRE_GARANTIE  

(
  ID_SINISTRE      VARCHAR2(255 BYTE),
  ID_GARANTIE     VARCHAR2(255 BYTE),
  DATE_INS         DATE,
  DATE_FIN         DATE,
  SOURCE           VARCHAR2(255 BYTE),
  ID_SAT_LINK_SINISTRE_GARANTIE  VARCHAR2(255 BYTE),
  ANNEE            NUMBER,
  CODEINTE         VARCHAR2(255 BYTE),
  NUMESINI         VARCHAR2(255 BYTE),
  NATUSINI         VARCHAR2(255 BYTE),
  NUMEPOLI        VARCHAR2(255 BYTE),
  NUMEAVEN         VARCHAR2(255 BYTE),
  CODERISQ         VARCHAR2(255 BYTE),
  CODEGARA        VARCHAR2(255 BYTE),
  CODECATE         VARCHAR2(255 BYTE),
  DATESURV         DATE,
  DATEDECL         DATE,
  DATEEFFE        DATE,
  DATEECHE        DATE,
  SINPAY           NUMBER,
  SINPAY_ANT       NUMBER,
  RECENC           NUMBER,
  RECENC_ANT       NUMBER,
  SOLDE_PAIEMENTS  NUMBER,
  EVAL             NUMBER,
  SAP              NUMBER,
  AREC             NUMBER,
  COUTS_SINISTRES  NUMBER,
  CODTYPSO         VARCHAR2(30 BYTE),
  LIBTYPSO         VARCHAR2(30 BYTE),
  STATUT         VARCHAR2(255 BYTE)
)
;


DROP TABLE REASS_DB.REPORTING_REASS_M_BRANCHE1 CASCADE CONSTRAINTS;

CREATE TABLE REASS_DB.REPORTING_REASS_M_BRANCHE1
(
  CODEBRAN            NUMBER,
  CODEINTE            VARCHAR2(255 BYTE),
  NUMEPOLI            VARCHAR2(255 BYTE),
  NUMEAVEN            VARCHAR2(255 BYTE),
  ANNEE_EFFET         VARCHAR2(4 BYTE),
  STATUT_TRAITE       NUMBER,
  STATUT_NOS_CALCULS  NUMBER,
  STATUT_MILLIARD     NUMBER,
  SOURCE              VARCHAR2(255 BYTE),
  STATUT_COASS        VARCHAR2(255 BYTE),
  REASS       VARCHAR2(10 BYTE),
  STATUT              VARCHAR2(255 BYTE),
  PRM_NT_100          NUMBER,
  PRM_NT_COASS        NUMBER,
  PRIME_CEDEE     NUMBER,
 -- PRIME_CEDEE_FAC     NUMBER,
 -- PRIME_CEDEE_EDP     NUMBER,
  PRIME_DECOUVERT     NUMBER,
  PRIME_RETENTION     NUMBER
);
commit;